//auth
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const SET_LOGIN_ERROR = 'SET_LOGIN_ERROR';
export const LOGOUT = 'LOGOUT';


//theater
export const FETCH_SHOWS_START = 'FETCH_SHOWS_START';
export const FETCH_SHOWS_SUCCESS = 'FETCH_SHOWS_SUCCESS';
export const FETCH_SHOWS_FAIL = 'FETCH_SHOWS_FAIL';
export const FETCH_SHOW_START = 'FETCH_SHOW_START';
export const FETCH_SHOW_SUCCESS = 'FETCH_SHOW_SUCCESS';
export const FETCH_SHOW_FAIL = 'FETCH_SHOW_FAIL';
export const DELETE_SHOW_SUCCESS = 'DELETE_SHOW_SUCCESS';
export const CREATE_SHOW_SUCCESS = 'CREATE_SHOW_SUCCESS';
export const EDIT_SHOW_SUCCESS = 'EDIT_SHOW_SUCCESS';

export const FETCH_SCENES_SUCCESS = 'FETCH_SCENES_SUCCESS';
export const CREATE_SCENE_SUCCESS = 'CREATE_SCENE_SUCCESS';

export const FETCH_ACTORS_SUCCESS = "FETCH_ACTORS_SUCCESS";
export const CREATE_ACTOR_SUCCESS = "CREATE_ACTOR_SUCCESS";
export const DELETE_ACTOR_SUCCESS = "DELETE_ACTOR_SUCCESS";


//reservations
export const FETCH_RESERVATIONS_START = 'FETCH_RESERVATIONS_START';
export const FETCH_RESERVATIONS_SUCCESS = 'FETCH_RESERVATIONS_SUCCESS';
export const FETCH_RESERVATIONS_FAIL = 'FETCH_RESERVATIONS_FAIL';
export const MAKE_RESERVATION_SUCCESS = 'MAKE_RESERVATION_SUCCESS';
export const MAKE_RESERVATION_FAIL = 'MAKE_RESERVATION_FAIL';
export const RESET_ERROR_AND_SUCCES = 'RESET_ERROR_AND_SUCCES';


//ratings
export const DID_USER_RATE_SHOW = 'DID_USER_RATE_SHOW';
export const AVG_AND_COUNT_FOR_SHOW = 'AVG_AND_COUNT_FOR_SHOW';
export const GIVE_RATING_FOR_SHOW = 'GIVE_RATING_FOR_SHOW';
