//auth
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const SET_LOGIN_ERROR = 'SET_LOGIN_ERROR';
export const LOGOUT = 'LOGOUT';

//theater
export const FETCH_SHOWS_START = 'FETCH_SHOWS_START';
export const FETCH_SHOWS_SUCCESS = 'FETCH_SHOWS_SUCCESS';
export const FETCH_SHOWS_FAIL = 'FETCH_SHOWS_FAIL';
export const DELETE_SHOW_SUCCESS = 'DELETE_SHOW_SUCCESS';
export const CREATE_SHOW_SUCCESS = 'CREATE_SHOW_SUCCESS';

export const FETCH_SCENES_SUCCESS = 'FETCH_SCENES_SUCCESS';
export const CREATE_SCENE_SUCCESS = 'CREATE_SCENE_SUCCESS';

export const FETCH_ACTORS_SUCCESS = "FETCH_ACTORS_SUCCESS";
export const CREATE_ACTOR_SUCCESS = "CREATE_ACTOR_SUCCESS";
export const DELETE_ACTOR_SUCCESS = "DELETE_ACTOR_SUCCESS";
